openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /compras:
    get:
      tags:
      - compra-rest-controller
      operationId: obtenerHistorialCompra
      parameters:
      - name: email
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: El recurso ha sido creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompraRestController'
    post:
      tags:
      - compra-rest-controller
      operationId: crearCompra
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompraDTO'
        required: true
      responses:
        "201":
          description: El recurso ha sido creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompraRestController'
  /productos:
    get:
      tags:
      - producto-rest-controller
      operationId: listarProductos
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /compras/{numeroFactura}:
    get:
      tags:
      - compra-rest-controller
      operationId: obtenerDetalleCompra
      parameters:
      - name: numeroFactura
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompraRestController'
  /compras/{idCompra}:
    get:
      tags:
      - compra-rest-controller
      operationId: obtenerEstadoCompra
      parameters:
      - name: idCompra
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompraRestController'
    delete:
      tags:
      - compra-rest-controller
      operationId: cancelarCompra
      parameters:
      - name: idCompra
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: El recurso ha sido eliminado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompraRestController'
components:
  schemas:
    CompraDTO:
      type: object
      properties:
        medioPago:
          type: string
          enum:
          - TARJETA
          - EFECTIVO
        usuario:
          $ref: '#/components/schemas/UsuarioDTO'
        productos:
          type: array
          items:
            $ref: '#/components/schemas/ProductoDTO'
    ProductoDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        referencia:
          type: string
        precio:
          type: number
        cantidadCompra:
          type: integer
          format: int32
    UsuarioDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        correo:
          type: string
    CompraRestController:
      type: object
      properties:
        compraServicio:
          $ref: '#/components/schemas/CompraServicio'
    CompraServicio:
      type: object
